<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <UseWindowsForms>False</UseWindowsForms>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <Optimize>False</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <Optimize>False</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WpfTerminalControl\**" />
    <EmbeddedResource Remove="WpfTerminalControl\**" />
    <None Remove="WpfTerminalControl\**" />
    <Page Remove="WpfTerminalControl\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MicaWPF" Version="6.3.2" />
    <PackageReference Include="Microsoft.Terminal.Wpf" Version="0.1.0" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
    <PackageReference Include="MaxMind.Db" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="IPDataBase\**\*.mmdb" CopyToOutputDirectory="PreserveNewest" LinkBase="IPDataBase" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo &quot;正在运行Rust编译批处理...&quot;&#xD;&#xA;call &quot;$(ProjectDir)linux-monitor\compile.bat&quot; &quot;$(ProjectDir)linux-monitor&quot;&#xD;&#xA;if %25errorlevel%25 neq 0 (&#xD;&#xA;    echo &quot;Rust编译失败,退出生成解决方案...&quot;&#xD;&#xA;    exit /b %25errorlevel%25&#xD;&#xA;)&#xD;&#xA;echo &quot;Rust编译成功&quot;&#xD;&#xA;&#xD;&#xA;echo &quot;拷贝Rust Linux程序到输出目录...&quot;&#xD;&#xA;copy /Y &quot;$(ProjectDir)linux-monitor\linux-monitor&quot; &quot;$(TargetDir)&quot;" />
  </Target>

</Project>
